### ISSUE TITLE
cannot import name Container

### ISSUE THREAD

**Issue by VRM1** [slim1017/VaDE#16]
Hi, 

I am trying to execute your code for the following versions of theano, keras and sklearn

Keras - '2.2.4'
Theano - '1.0.3'
sklearn - '0.20.1'

I had to make some modifications to your VaDE.py code by changing GMM to GaussianMixture. Now, when replacing the training.py at keras/engine/ with the one included in your code results in the following error. Can you please help me out with this? 

Using Theano backend.
Traceback (most recent call last):
  File "VaDE.py", line 14, in <module>
    from keras.callbacks import Callback
  File "/Users/vineeth/anaconda2/envs/DeepLearning/lib/python2.7/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/Users/vineeth/anaconda2/envs/DeepLearning/lib/python2.7/site-packages/keras/utils/__init__.py", line 27, in <module>
    from .multi_gpu_utils import multi_gpu_model
  File "/Users/vineeth/anaconda2/envs/DeepLearning/lib/python2.7/site-packages/keras/utils/multi_gpu_utils.py", line 7, in <module>
    from ..layers.merge import concatenate
  File "/Users/vineeth/anaconda2/envs/DeepLearning/lib/python2.7/site-packages/keras/layers/__init__.py", line 4, in <module>
    from ..engine.base_layer import Layer
  File "/Users/vineeth/anaconda2/envs/DeepLearning/lib/python2.7/site-packages/keras/engine/__init__.py", line 8, in <module>
    from .training import Model
  File "/Users/vineeth/anaconda2/envs/DeepLearning/lib/python2.7/site-packages/keras/engine/training.py", line 15, in <module>
    from .topology import Container
ImportError: cannot import name Container

I appreciate your help in advance.

Thanks
Vineeth

**Comment by hitokun-s** [comment]
It seems that 'Container' has changed into 'Network' in keras >= 2.2.  
So change your code from 

    from keras.engine.topology import Container

to

    from keras.engine.network import Network

and use 'Network' as same as 'Container'.
