### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute 'broadcastable'

### ISSUE THREAD

**Issue by TideDancer** [slim1017/VaDE#6]
When I run $ python3 ./VaDE_test_mnist.py
it shows error:
Using TensorFlow backend.
Traceback (most recent call last):
  File "./VaDE_test_mnist.py", line 124, in <module>
    p_c_z = Lambda(get_gamma, output_shape=(n_centroid,))(z_mean)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/topology.py", line 602, in __call__
    output = self.call(inputs, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/keras/layers/core.py", line 650, in call
    return self.function(inputs, **arguments)
  File "./VaDE_test_mnist.py", line 90, in get_gamma
    temp_Z=T.transpose(K.repeat(tempz,n_centroid),[0,2,1])
  File "/usr/local/lib/python3.5/dist-packages/theano/tensor/basic.py", line 3567, in transpose
    ret = DimShuffle(x.broadcastable, axes)(x)
AttributeError: 'Tensor' object has no attribute 'broadcastable'

Any clue on this? Thanks a lot.

**Comment by TideDancer** [comment]
figured, needs to config keras using theano as backend.

**Comment by JasonKwok17** [comment]
I solved this error by that too,but I have another error now,could you help me?Thanks a lot!!!
![image](https://user-images.githubusercontent.com/34647723/37082706-318ddfc8-2228-11e8-8382-2ea5688c32e6.png)
