### ISSUE TITLE
AttributeError: 'tensor' object has no attribute 'broadcastable'

### ISSUE THREAD

**Issue by tansinjahan** [slim1017/VaDE#9]
I am getting this error while running VaDE.py in windows. Can you please suggest how to solve the problem?

C:\Users\GIGL\VaDE-master>python VaDE.py dataset
Using TensorFlow backend.
WARNING (theano.configdefaults): g++ not available, if using conda: `conda insta
ll m2w64-toolchain`
C:\Program Files\Python35\lib\site-packages\theano\configdefaults.py:560: UserWa
rning: DeprecationWarning: there is no c++ compiler.This is deprecated and with
Theano 0.11 a c++ compiler will be mandatory
  warnings.warn("DeprecationWarning: there is no c++ compiler."
WARNING (theano.configdefaults): g++ not detected ! Theano will be unable to exe
cute optimized C-implementations (for both CPU and GPU) and will default to Pyth
on implementations. Performance will be severely degraded. To remove this warnin
g, set Theano flags cxx to an empty string.
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS fu
nctions.
training on: mnist
Traceback (most recent call last):
  File "VaDE.py", line 249, in <module>
    Gamma = Lambda(get_gamma, output_shape=(n_centroid,))(z)
  File "C:\Program Files\Python35\lib\site-packages\keras\engine\topology.py", l
ine 603, in __call__
    output = self.call(inputs, **kwargs)
  File "C:\Program Files\Python35\lib\site-packages\keras\layers\core.py", line
651, in call
    return self.function(inputs, **arguments)
  File "VaDE.py", line 111, in get_gamma
    temp_Z=T.transpose(K.repeat(tempz,n_centroid),[0,2,1])
  File "C:\Program Files\Python35\lib\site-packages\theano\tensor\basic.py", lin
e 3691, in transpose
    ret = DimShuffle(x.broadcastable, axes)(x)
AttributeError: 'Tensor' object has no attribute 'broadcastable'

**Comment by isamu** [comment]
When I using  TensorFlow backend, I got similar error.
Try to change keras backend to theano.

**Comment by JasonKwok17** [comment]
@tansinjahan ,I have the same problem as you,and @isamu  I did as he said,change keras backend from TensorFlow to Theano,I dont have this error now,but I have another error!
![image](https://user-images.githubusercontent.com/34647723/37080425-30753e30-2221-11e8-98bc-6b686afd2378.png)
please help me,thanks lot!

**Comment by isamu** [comment]
@JasonKwok17 Are you using correct versions?
Python-3.4.4
keras-1.1.0
scikit-learn-1.17.1

When I was using different versions, I got same error. Please comfirm those.

To install those, I used pyenv and pip-sync, then I get valid version environment.
Please check my PR  https://github.com/slim1017/VaDE/pull/12

pyenv install 3.4.4
pyenv virtualenv 3.4.4 VaDE
pyenv local VaDE
pip install pip-tools
pip-sync requirements/*.txt

**Comment by ReyhanehAbbasi** [comment]
Dear @isamu I had some troubles installing pyenv (in homebrew installation). 
I also tried to install python3.4.4, using [this instruction](http://ernie55ernie.github.io/python/2016/11/11/install-python-packages-for-local-user-without-sudo.html) but there is a problem with installing packages. because every package I install, it can be imported on python 3.5 (which was on our server initially). do you any other solutions for solving this issue?
Using the above-mentioned version of python and modules, could you use VaDE for your data?
Please consider that I am not root!

**Comment by ReyhanehAbbasi** [comment]
Dear @isamu I had some troubles installing python throguh pyenv:
`ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?

Please consult to the Wiki page to fix the problem.
https://github.com/pyenv/pyenv/wiki/Common-build-problems
`
I also tried to install python3.4.4, using this instruction but there is a problem with installing packages. because every package I install, it can be imported on python 3.5 (which was on our server initially). do you any other solutions for solving this issue?
Using the above-mentioned version of python and modules, could you use VaDE for your data?
Please consider that I am not root!

**Comment by isamu** [comment]
@ROAbb  as https://github.com/pyenv/pyenv/wiki/Common-build-problems, you should like to set CFLAGS and LDFLAGS when you install pyenv.
If your system has not the OpenSSL lib, you  should like to  OpenSSL lib under your home dir and set CFLAGS and LDFLAGS.
